[Map Local]
^https?:\/\/(?:www|m)\.baidu\.com\/?(?:\?[^#]*)?$ data-type=file data="https://raw.githubusercontent.com/Jimmyzsan/baidu-clean-search/main/index.html" header="Content-Type: text/html; charset=utf-8"

[MITM]
hostname = %APPEND% www.baidu.com, m.baidu.com
